import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
      // className={`${inter.className} flex min-h-full flex-col items-center justify-center bg-black text-gray-200 antialiased`}
      // className={`${inter.className} flex min-h-full flex-col items-center justify-center bg-black text-gray-200 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
